#datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Deco3801?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: yuyu2015@
#    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml